### ISSUE TITLE
Just "ERROR" on Citra

### ISSUE THREAD

**Issue by yepdorian** [EverOddish/PokeStreamer-Tools#5]
![image](https://user-images.githubusercontent.com/64704851/80872782-7bf6df80-8cb4-11ea-9d26-6f0293e5b775.png)

I did everything in the setup guide and it says "ERROR" at the end. My party files weren't modified

**Comment by TDS-Dyno** [comment]
same here, except there are all 0s

**Comment by KyubTenrecFox** [comment]
I have the same issue, but I know where it comes from :
```py
shutil.copyfile("000.png", "p" + str(i + 1) + ".png") #line 431
shutil.copyfile(str(species_num) + ".png", "p" + str(i + 1) + ".png") #line 435
shutil.copyfile(party[i].species().lower() + ".png", "p" + str(i + 1) + ".png") #line 443
```
The function is not working, and I don't know why.
